/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An application in the software system.
 */
export interface Application {
  /**
   * The application version, typically as a YYYY.M.D format
   */
  version: string;
  "application-flow"?: Tool[];
  /**
   * The hardware devices that the application can run on.
   */
  platforms: ("touch-screen-phone" | "cloud-server")[];
  [k: string]: unknown;
}
/**
 * A tool that can be part of an application.
 */
export interface Tool {
  button?: {
    label?: string;
    [k: string]: unknown;
  };
  "qr-code-camera-scanner"?: boolean;
  "key-string-generator"?: {
    numberOfCharacters?: number;
    [k: string]: unknown;
  };
  "qr-code-generator"?: boolean;
  "image-viewer"?: boolean;
  "data-encryption"?: {
    encryptionMethod?: "finger-print" | "numeric-code" | "security-question" | "password" | "hash-key";
    [k: string]: unknown;
  };
  "data-storage"?: {
    accessFrequency?: "low" | "medium" | "high";
    capacity?: {
      amount?: number;
      unit?: "mb" | "gb" | "tb";
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
