kind: Deployment
apiVersion: apps/v1
metadata:
  name: static-web-server-deployment
  labels:
    app: static-web-server-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-web-server-pod
  template:
    metadata:
      labels:
        app: static-web-server-pod
    spec:
      containers:
        - name: static-web-server-pod
          image: stojanragnvlad/static-web-server:latest
          ports:
            - containerPort: 80
